blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/uvEakpv7Nu
    about: Get help from the community on Discord
  - name: Website
    url: https://slaukoscript.com
    about: Visit our website for more information
